# Создать легковесный тег на основе выбранного тега
name: Bump version

on:
  workflow_dispatch:
    inputs:
      level:
        required: true
        type: choice
        description: 'тег docker-образа для развертывания'
        options:
          - patch
          - minor
          - major
      label:
        required: false
        type: string
        description: 'метка для тега (прим.: alpha в v0.0.1-alpha)'

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CONTENT_WRITE_TOKEN }}
          TAG_PREFIX: v
          TAG_CONTEXT: branch
          PRERELEASE: ${{ inputs.label != '' }}
          PRERELEASE_SUFFIX: ${{ inputs.label }}
          DEFAULT_BUMP: ${{ inputs.level }}
          MAJOR_STRING_TOKEN: _
          MINOR_STRING_TOKEN: _
          PATCH_STRING_TOKEN: _
          NONE_STRING_TOKEN: _
          FORCE_WITHOUT_CHANGES: true
