name: Delivery and build image

on:
  push:
    tags:
      - 'v*'  # все теги, начинающиеся с 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # чтобы получить все теги

      - name: Extract version
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Copy code to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/opt/npchat/releases/${{ steps.version.outputs.VERSION }}"

      - name: Build Docker image
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/npchat/releases/${{ steps.version.outputs.VERSION }}
            docker build -t npchat:${{ steps.version.outputs.VERSION }} -f Containerfile --build-arg VERSION=${{ steps.version.outputs.VERSION }} .