name: Стянуть образ и запустить docker-контейнер в рабочей среде

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag
        run: |
          if [ -z "${{ github.ref_name }}" ]; then
            echo "❌ Не найден тег/ветка. Этот workflow может быть запущен только на теге/ветке git."
            exit 1
          fi

      - name: Deploy with rollback
        uses: appleboy/ssh-action@v1.2.2
        # continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            NEW_VERSION=${{ github.ref_name }}
            APP_NAME=npchat
            PREV_VERSION=$(docker inspect --format='{{.Config.Image}}' $APP_NAME 2>/dev/null | sed 's/^.*://')
            
            echo "Развертывание npchat:$NEW_VERSION..."
            
            # Останавливаем текущий контейнер
            docker stop $APP_NAME || true
            docker rm $APP_NAME || true
            
            # Загрузить переменные окружения, чтобы были доступны в docker-compose
            set -o allexport
            source /opt/npchat/.env.production
            set +o allexport
            
            # Название образа
            export IMAGE_NAME=${{ vars.DOCKER_IMAGE_NAME }}
            
            # Запускаем новый
            RESULT=$(IMAGE_TAG=$NEW_VERSION docker compose -f /opt/npchat/infra/npchat/docker-compose.yaml up --wait npc.npchat)
            if [ $? -eq 0 ]; then
              echo "✅ Успешно развернут npchat:$NEW_VERSION ."
              exit 0
            fi
            
            echo "❌ Deployment of $NEW_VERSION failed."
            
            # Пытаемся восстановить предыдущий контейнер
            if [ -n "$PREV_VERSION" ]; then
              echo "🔄 Откат к npchat:$PREV_VERSION..."
              IMAGE_TAG=$PREV_VERSION docker compose -f /opt/npchat/infra/npchat/docker-compose.yaml up --wait npc.npchat
            fi