name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Validate tag
        run: |
          if [ -z "${{ steps.version.outputs.VERSION }}" ]; then
            echo "❌ No tag found. This workflow should be triggered by a git tag."
            exit 1
          fi

      - name: Deploy with rollback
        uses: appleboy/ssh-action@v1.2.2
        # continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            NEW_VERSION=${{ steps.version.outputs.VERSION }}
            APP_NAME=npchat
            PREV_VERSION=$(docker inspect --format='{{.Config.Image}}' $APP_NAME 2>/dev/null | sed 's/^.*://')

            echo "Deploying version $NEW_VERSION..."

            # Останавливаем текущий контейнер
            docker stop $APP_NAME || true
            docker rm $APP_NAME || true

            # Запускаем новый
            RESULT=$(IMAGE_TAG=$NEW_VERSION docker compose -f /opt/npchat/releases/"$NEW_VERSION"/infra/docker-compose.yaml up --wait npc.npchat)
            if [ $? -eq 0 ]; then
              echo "✅ Deployment of $NEW_VERSION successful."
              exit 0
            fi

            echo "❌ Deployment of $NEW_VERSION failed."

            # Пытаемся восстановить предыдущий контейнер
            if [ -n "$PREV_VERSION" ]; then
              echo "🔄 Rolling back to previous version $PREV_VERSION..."
              IMAGE_TAG=$PREV_VERSION docker compose -f /opt/npchat/releases/"$PREV_VERSION"/infra/docker-compose.yaml up --wait npc.npchat
            fi
        
    
