name: Стянуть образ и запустить docker-контейнер в рабочей среде

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag
        run: |
          if [ -z "${{ github.ref_name }}" ]; then
            echo "❌ Не найден тег/ветка. Этот workflow может быть запущен только на теге/ветке git."
            exit 1
          fi

      - name: Deploy with rollback
        uses: appleboy/ssh-action@v1.2.2
        # continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            NEW_IMAGE=${{ github.ref_name }}
            CONTAINER_NAME=npc.npchat
            PREV_IMAGE=$(docker inspect --format='{{.Config.Image}}' $CONTAINER_NAME 2>/dev/null | sed 's/^.*://')
            
            echo "Развертывание $CONTAINER_NAME:$NEW_IMAGE..."
            
            # Останавливаем текущий контейнер
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            
            # Загрузить переменные окружения, чтобы были доступны в docker-compose
            set -o allexport
            source /opt/npchat/.env.production
            set +o allexport
            
            # Название образа
            export IMAGE_NAME=${{ vars.DOCKER_IMAGE_NAME }}
            
            # Запускаем новый
            RESULT=$(IMAGE_TAG=$NEW_IMAGE docker compose -f /opt/npchat/infra/npchat/docker-compose.yaml up --wait npc.npchat)
            if [ $? -eq 0 ]; then
              echo "✅ Успешно развернут $CONTAINER_NAME:$NEW_IMAGE ."
              exit 0
            fi
            
            echo "❌ Развернуть $CONTAINER_NAME:$NEW_IMAGE не удалось."
            
            # Пытаемся восстановить предыдущий контейнер
            if [ -n "$PREV_IMAGE" ]; then
              echo "🔄 Откат к npchat:$PREV_IMAGE..."
              IMAGE_TAG=$PREV_IMAGE docker compose -f /opt/npchat/infra/npchat/docker-compose.yaml up --wait npc.npchat
            fi