name: on-pr-merged.yml

on:
  pull_request:
    paths-ignore:
      - ".gitignore"
      - ".mockery.yaml"
      - "Containerfile"
      - "LICENSE"
      - "Makefile"
      - "README.md"
    types:
      - closed
    branches:
      - master

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.merged == true
        uses: .github/workflows/ci-delivery.yml