# Создает легковесные теги на основе существующих в репозитории
name: CI/Tag bumping

on:
  pull_request:
    types:
      - closed
    branches:
      - master

permissions:
  contents: write


jobs:
  bump_version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CONTENT_WRITE_TOKEN }}
          TAG_PREFIX: v
          PRERELEASE: true
          DEFAULT_BUMP: patch
